default_context:
  project_name: 'SupplyLink'
  project_slug: 'supplylink'
  domain_main: 'supplylink.com'
  domain_staging: 'stag.supplylink.com'
  docker_swarm_stack_name_main: 'supplylink-com'
  docker_swarm_stack_name_staging: 'stag-supplylink-com'
  secret_key: '26305caebca78e64e79d9883bb98763d08b6f138caf309bf271d53d10df3cb68'
  first_superuser: 'admin@supplylink.com'
  first_superuser_password: 'f1c73cf061443b35d8c2bfcc6c2520a923b37ab298dba0a29dd6f13b9a40048e'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.supplylink.com", "https://stag.supplylink.com", "https://supplylink.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@supplylink.com'
  postgres_password: 'dfc431ce514d375b67a9ab696081f8d86d6ac8b628e191bb533216c280cdcee6'
  pgadmin_default_user: 'admin@supplylink.com'
  pgadmin_default_user_password: 'f1c73cf061443b35d8c2bfcc6c2520a923b37ab298dba0a29dd6f13b9a40048e'
  traefik_constraint_tag: 'supplylink.com'
  traefik_constraint_tag_staging: 'stag.supplylink.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:f1c73cf061443b35d8c2bfcc6c2520a923b37ab298dba0a29dd6f13b9a40048e'
  sentry_dsn: ''
  docker_image_prefix: 'sl'
  docker_image_backend: 'slbackend'
  docker_image_celeryworker: 'slceleryworker'
  docker_image_frontend: 'slfrontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
